version: '3'

services:
  
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8888:8888/udp
    #command: tail -f
    #restart: always
    command: python -u test.py
