version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: tail -f
    #restart: always
    #command: python run_server.py
