version: '3'

services:

  homenetworkserver:
    container_name: homenetworkserver
    build:
      context: ./HomeNetworkServer
      dockerfile: Dockerfile
    volumes:
      # notice : this will delete the pycose git repo from the container
      - ./HomeNetworkServer:/app
    ports:
      - 9999:9999/udp
      - 8080:8080
      - 8765:8765
    env_file: .env
    # networks:
    #   - udpclient_some-net
    #command: tail -f
    #restart: always
    command: python3 -u server.py


  applicationserver:
    container_name: applicationserver
    build:
      context: ./ApplicationServer
      dockerfile: Dockerfile
    volumes:
      - './ApplicationServer:/app'
      - '/app/node_modules'
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/app
    ports:
      - 80:80
    #stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: .env
    depends_on:
      - homenetworkserver
    #command: tail -f
    command: npm start


  payment:
    container_name: payment
    build:
      context: ./Payment
      dockerfile: Dockerfile
    volumes:
      - './Payment:/app'
      - '/app/node_modules'
    env_file: .env
    ports:
      - 3000:3000
    #stdin_open: true
    depends_on:
      - homenetworkserver
    #command: tail -f
    command: node payment.js

# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
# networks:
#   udpclient_some-net:
#     external: true
