version: '3'

services:

  homenetworkserver:
    container_name: homenetworkserver
    build:
      context: ./HomeNetworkServer
      dockerfile: Dockerfile
    volumes:
      # notice : this will delete the pycose git repo from the container
      - ./HomeNetworkServer:/app
    ports:
      - 8080:8080
      - 8765:8765
    env_file: .env
    command: python3 -u server.py


  applicationserver:
    container_name: applicationserver
    build:
      context: ./ApplicationServer
      dockerfile: Dockerfile
    volumes:
      - './ApplicationServer:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: .env
    depends_on:
      - homenetworkserver
    command: npm start


  payment:
    container_name: payment
    build:
      context: ./Payment
      dockerfile: Dockerfile
    volumes:
      - './Payment:/app'
      - '/app/node_modules'
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - homenetworkserver
    command: node payment.js
