version: '2'

services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 7777:7777/udp
    networks:
      - some-net
    #command: tail -f
    #restart: always
    command: python -u client.py


networks:
  some-net:
    driver: bridge